### ISSUE TITLE
Could not find formula for amino acid: _

### ISSUE THREAD

**Issue by helloworld1631** [yeastrc/proxl-import-merox#1]
Hi Michael,

I tried the latest merox2ProxlXML, but an error was encountered: "Could not find formula for amino acid: _" 
I am not sure if it is due to my .zhrm file or some parameters.  

#########
> java -jar .\merox2ProxlXML.jar -f .\DB_7761.fasta -o results_proxl.xml -r .\combined1_5.zhrm
Starting up MeroX 2 to proxl XML Converter (version 1.0.4)

Please report problems by submitting issues on GitHub at:
https://github.com/yeastrc/proxl-import-MeroX
Or by email to Michael Riffle <mriffle@uw.edu>

Error encountered:
Could not find formula for amino acid: _

#########

Thank you,
Kirin

**Comment by mriffle** [comment]
Hi Kirin is it possible to share the .zhrm file with me?

**Comment by helloworld1631** [comment]
Sure. Sent to your email.

**Comment by helloworld1631** [comment]
Hi Michael, do you receive my eamil?

**Comment by mriffle** [comment]
Yes, I have been in meetings today, will respond when I get a chance.

**Comment by mriffle** [comment]
Kirin, I have looked at the zhrm file and I don't see anything that is obvious that would cause this error. This error would be produced if a modified residue in a peptide was reported as "_", which I don't see ever happening in this file. To investigate this further I would also need the FASTA file and would need to try to run the conversion myself. I will need to isolate which specific result is causing the issue.

**Comment by helloworld1631** [comment]
Sure, I sent it to you.

**Comment by mriffle** [comment]
Kirin, the problem looks to be caused by this parameter setting in the properties file:

```
POSTRANSLATIONALMODIFICATION    //List of possible posttranslational modifications (peptide level, no localization attempted)
  CHNO;{
END
```

I think this means it looks for the mass of a CHNO that may be on the peptide at any residue/terminus. This results in peptides reported as: `{MWRAKLR]_CHNO` -- it is this _CHNO that is breaking the converter program.

Proxl doesn't currently support the idea of an unlocalized modification so I don't think uploading data searched with that setting will work. I can add developing support for that to my TODO list, but it may be some time before I get to that.

**Comment by helloworld1631** [comment]
Thank you!  I want to consider this modification at protein N-terminus " { ".  But if it causes the unlocalization problem, I will remove this modification and test again.

**Comment by mriffle** [comment]
The way it is shown in the configuration file, it looks like CHNO was searched for as an unlocalized PTM. I think it should be possible to search for that as a localized modification restricted to the N-terminus, which should be fine for proxl.

**Comment by helloworld1631** [comment]
Now it works well. My data can be visualized on Proxyl now. I will close this issue, as it seems the problem comes from my MeroX search parameters/its features.  Thanks again!
